#!/bin/bash

export DISPLAY=:0

# get dates: last modified of biodata file and today
modified=$(stat "$HOME"/dropbox/Apps/TrainingLogTest/biodata.xml | grep 'Modify' | cut -d ' ' -f 2)
today=$(date +%Y-%m-%d)

# if the file hasn't been modified today, do stuff
if [[ "$modified" != "$today" ]]; then
    if [[ -f "$HOME"/dropbox/Apps/TrainingLogTest/.biodata.xml.swp ]]; then
      exit 0
    fi

    # say "..."
    curl -A RG translate.google.com/translate_tts -d "tl=en&q=Please enter biodata" 2> /dev/null | mpg123 - 2> /dev/null
    # open biodata
    /usr/bin/xfce4-terminal -e "bash -c 'vim $HOME/dropbox/Apps/TrainingLogTest/biodata.xml; exec bash'" &
    # write to STDOUT (for log)
    echo "Opened biodata.xml"
fi

