#!/bin/bash

if [ -r "$HOME/.dbus/Xdbus" ]; then
    . "$HOME/.dbus/Xdbus"
fi

# ensure new-day has been run
new-day

# execute command and store command output
"$@" 1> /tmp/out 2> /tmp/err

# get output, error, and date
OUT=$(cat /tmp/out)
ERR=$(cat /tmp/err)
DATE=$(date "+%A, %B %d, %Y [%T]")
LOG="/var/log/cron-history"

# update .cron history
echo "*** $DATE $*" >> $LOG

if [ "$OUT" ]; then
    notify-send -u low "$OUT"
    echo "$OUT" >> $LOG
fi

if [ "$ERR" ]; then
    CMD="Error while running cron task \"$*\":"$'\n'"$ERR"
    notify-send -u critical "$CMD"
    echo "--> ERROR: $ERR" >> $LOG
fi

