#!/bin/bash

my_ls() {
    # save current directory then cd to "$1"
    pushd "$1" >/dev/null

    if find . -maxdepth 1 | grep -q "^./.git$" ; then
        REPO=$(basename "$PWD")
        echo "--> Repo $REPO, do you want to pull? (y/n)"
        read ANSWER
        if echo "$ANSWER" | grep -qi "^y$" ; then
            git pull
        fi

        echo ""
    elif find . -maxdepth 1 | grep "^./.hg$" ; then
        echo "ignoring mercurial repos" > /dev/null
    else
        for dir in */ ; do
            my_ls "$dir"
        done
    fi

    # restore directory
    popd >/dev/null
}

my_ls "$1"

