#!/bin/bash

# recursively checks directories to see whether they're git repositoriesj
# and whether they're "mine". if so, the repo's commits are imported to git-stats

# remove old git-stats
if [ -f "$HOME/.git-stats" ]; then
  echo "Removing old git-stats file"
  rm "$HOME/.git-stats"
fi

# manually add some repos...
REPO="$HOME/git/cu/305cde/Agora"
echo "Manually importing commits from $REPO"
pushd "$REPO" > /dev/null
git-stats-importer > /dev/null
popd > /dev/null

my_ls() {
  # save current directory then cd to "$1"
  pushd "$1" > /dev/null

  if find . -maxdepth 1 | grep -q "^./.git$" ; then
    echo "Importing commits from $PWD"
    git-stats-importer > /dev/null
  elif find . -maxdepth 1 | grep -q "^./.hg$" ; then
    echo "ignoring mercurial repos" > /dev/null

  else
    for file in * ; do
      #test -d "$file" && echo "$file"
      if [[ -d "$file" ]]; then
        my_ls "$file"
      fi
    done
  fi

  # restore directory
  popd > /dev/null
}

my_ls "$1"

