#!/bin/bash

RES=""

my_ls() {
    # save current directory then cd to "$1"
    pushd "$1" >/dev/null

    if [ `find . -maxdepth 1 | grep "^./.git$"` ]; then
        echo "--> Repo "`basename $PWD`", do you want to pull? (y/n)"
        read ANSWER
        if [ `echo $ANSWER | grep -i "^y$"` ] ; then
            git pull
            echo ""
        fi
    elif [ `find . -maxdepth 1 | grep "^./.hg$"` ]; then
        echo "ignoring mercurial repos" > /dev/null
    else
        for file in * ; do
            #test -d "$file" && echo "$file"
            if [[ -d "$file" ]]; then
                my_ls "$file"
            fi
        done
    fi

    # restore directory
    popd >/dev/null
}

my_ls "$1"

if [ "$RES" ]; then
    echo "${RES:1}"
fi

