#!/bin/bash

RES=""

my_ls() {
    # save current directory then cd to "$1"
    pushd "$1" >/dev/null

    if [ `find . -maxdepth 1 | grep "^./.git$"` ]; then
        CNT=`git shortlog origin/master..HEAD -s | sed -e "s/\s*[a-zA-Z]*//g"`
        if [ $CNT ]; then
            RES="$RES"$'\n'`basename $PWD`": $CNT commits"
        fi
    elif [ `find . -maxdepth 1 | grep "^./.hg$"` ]; then
        echo "ignoring mercurial repos" > /dev/null

    else
        for file in * ; do
            #test -d "$file" && echo "$file"
            if [[ -d "$file" ]]; then
                my_ls "$file"
            fi
        done
    fi

    # restore directory
    popd >/dev/null
}

my_ls "$1"

if [ "$RES" ]; then
    echo "${RES:1}"
fi

