#!/bin/bash

RES=""

my_ls() {
    # save current directory then cd to "$1"
    pushd "$1" >/dev/null

    if find . -maxdepth 1 | grep -q "^./.git$" ; then
        BRANCH=$(git branch | grep "\*" | cut -c 3-)
        CNT=$(git shortlog origin/"$BRANCH"..HEAD -s | sed -e "s/\s*[a-zA-Z]*//g")
        if [ "$CNT"  ]; then
            REPO=$(basename "$PWD")
            RES="$RES"$'\n'$REPO": $CNT commits"
        fi
    elif find . -maxdepth 1 | grep -q "^./.hg$" ; then
        echo "ignoring mercurial repos" > /dev/null

    else
        for file in * ; do
            #test -d "$file" && echo "$file"
            if [[ -d "$file" ]]; then
                my_ls "$file"
            fi
        done
    fi

    # restore directory
    popd >/dev/null
}

my_ls "$1"

if [ "$RES" ]; then
    echo "${RES:1}"
fi

