#!/bin/bash
# adapted from: https://wiki.archlinux.org/index.php/PulseAudio/Examples#Automatically_switch_audio_to_HDMI

USER_NAME=$(whoami)
USER_ID=$(id -u "$USER_NAME")
export PULSE_SERVER="unix:/run/user/$USER_ID/pulse/native"

if [[ $(grep -E '^connected$' /sys/class/drm/card0/*HDMI*/status) ]]; then
  sudo -u "$USER_NAME" pactl --server "$PULSE_SERVER" set-card-profile 0 output:hdmi-stereo+input:analog-stereo
else
  sudo -u "$USER_NAME" pactl --server "$PULSE_SERVER" set-card-profile 0 output:analog-stereo+input:analog-stereo
fi
