#!/bin/bash

# switch between 1-monitor- and 2-monitor-mode

# get names and number of currently enabled outputs
IN="eDP1"
EXT="$(xrandr | egrep '\bconnected' | cut -d' ' -f1 | grep -v "$IN" | head -n 1)"
ENABLED=$(xrandr | grep "\*" | cut -d' ' -f1)
COUNT=$(xrandr | grep -c "\*")

# turn off all enabled external monitors that are disconnected
for out in $ENABLED; do
  if (xrandr | grep "$out disconnected"); then
    xrandr --output "$out" --off
  fi
done

external-enable () {
  if [ "z$EXT" == "z" ]; then
    notify-send "No external monitor available"
    return
  fi
  xrandr --output "$EXT" --auto --above "$IN"
  notify-send "Enabled external monitor $EXT"
}
external-disable () {
  xrandr --output "$EXT" --off
  notify-send "Disabled external monitor $EXT"
}

xrandr --output "$IN" --auto --primary --set "scaling mode" "Full aspect"
case $1 in
  enable)
    external-enable
    ;;
  disable)
    external-disable
    ;;
  *)
    # toggle
    if [ "$COUNT" -eq 1 ]; then
      # if status is empty it's disabled: enable external monitor
      external-enable
    else
      # status is not empty it's enabled: disable external monitor
      external-disable
    fi
    ;;
esac

