#!/bin/bash

IN="LVDS1"
EXT="VGA1"

if (xrandr | grep "$EXT disconnected"); then
    xrandr --output $EXT --off 
else
    # gets info of second enabled monitor
    SND=$(xrandr | grep "\*"| sed -n '2p')
    
    if [[ "$SND" = "" ]]; then
        xrandr --output $IN --auto --primary --set "scaling mode" "Full aspect" --output $EXT --auto --pos 1602x0 --set "scaling mode" "Full aspect"
    else
        xrandr --output $IN --auto --primary --set "scaling mode" "Full aspect" --output $EXT --off
    fi
fi
