#!/usr/bin/env bash

set -e

trap 'notify-send "Error while connecting to NAS"' ERR

if ! ping nas.cofa -c 1 -w 1 &> /dev/null ; then
  notify-send "Unable to reach NAS"
  exit 1
fi

case $1 in
  connect)
    COMMAND=start
    notify-send "Connecting to NAS"
    ;;
  disconnect)
    COMMAND=stop
    notify-send "Disconnecting from NAS"
    ;;
  *)
    # toggle
    if mount | grep -q ^//nas.cofa/; then
      COMMAND=stop
      notify-send "Disconnecting from NAS"
    else
      COMMAND=start
      notify-send "Connecting to NAS"
    fi
    ;;
esac

sudo systemctl "$COMMAND" mnt-nas-{cofa,fabian,music,photo,video}.mount

