#!/bin/bash

modified=$(stat "$HOME/.cron_history" | grep 'Modify' | cut -d ' ' -f 2)
today=$(date +%Y-%m-%d)

if [[ "$modified" != "$today" ]]; then
    echo "-----------------------------------------------------------------------------------------------------" >> "$HOME/.cron_history"
fi

