#!/bin/bash

if [ -z "$1" ]; then
  CRON_LOG="/var/log/cron-history"
else
  CRON_LOG=$1
fi

modified=$(stat "$CRON_LOG" | grep 'Modify' | cut -d ' ' -f 2)
today=$(date +%Y-%m-%d)

if [[ "$modified" != "$today" ]]; then
    echo "-----------------------------------------------------------------------------------------------------" >> "$CRON_LOG"
fi

