#!/usr/bin/bash

# boots to the syslinux label windows
# if -h is specified, rather than powering off, the system is hibernated

if [[ "$1" == "-h" ]]; then
  extlinux --once windows /boot/syslinux && echo reboot > /sys/power/disk && echo disk > /sys/power/state
else
  extlinux --once windows /boot/syslinux && reboot
fi

