#!/bin/bash

radiocover=$1

coverXoffset=600

# find out whether clementine is running
running=$(dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames | grep clementine)
if [ "$running" == "" ]; then    
    exit 0
fi

# read dbus
data=$(qdbus org.mpris.clementine /Player org.freedesktop.MediaPlayer.GetMetadata)
stat=$(qdbus --literal org.mpris.clementine /Player org.freedesktop.MediaPlayer.GetStatus | cut -b 19)
pos=$(qdbus org.mpris.clementine /Player org.freedesktop.MediaPlayer.PositionGet)

if [ "$data" != "" ]; then
    # print header

    rp=$(echo "$data" | grep "location: " | grep "radioparadise")
    location=$(echo "$data" | grep "location: " | cut -b 11-)

    if [ "$rp" = "" ]; then
        # not listening to RP
        # format times
        sec=$((pos / 1000))
        min=$((sec / 60))
        sec=$((sec - 60 * min))
        if [ $sec -lt 10 ]; then
            zero=0
        fi
        forpos=$min':'$zero$sec
        zero=''
        sec=$(echo "$data" | grep "mtime: " | cut -b 8-)
        posperc=$((pos * 100 / sec))
        sec=$((sec / 1000))
        min=$((sec / 60))
        sec=$((sec - 60 * min))
        if [ $sec -lt 10 ]; then
            zero=0
        fi
        fortime="$min:$zero$sec"
    fi

    if [ "$stat" -eq 0 ]; then
        begin="\${font Open Sans:bold:size=8}"
        end="\${font}"
    fi

    # header
    echo -e "\n\${font Open Sans:Bold:size=10}\${color0}MUSIC\${hr 2}\$font\$color"

    # artist
    echo -n "\${goto 74}Artist:\${goto 116}$begin"
    echo -n "$data" | grep 'artist: ' | cut -b 9-

    # title
    echo -n "$end\${goto 74}Title:\${goto 116}$begin"
    echo -n "$data" | grep 'title: ' | cut -b 8-

    if [ "$rp" = "" ]; then
        # album
        echo -n "$end\${goto 74}Album:\${goto 116}$begin"
        echo -n "$data" | grep 'album: ' | cut -b 8-
        if [ "$stat" -eq 0 ]; then
            # time
            echo -n "$end\${goto 74}Time:\${goto 116}$begin"
            echo "$forpos / $fortime$end"

            # progressbar
            echo -n "\${goto 74}\${execbar echo $posperc}"
        else
            echo -en "\n\${alignc}PAUSED"
        fi
    else
        echo -n "$end\${goto 74}Stream:\${goto 116}$begin"
        echo -n "Radio Paradise$end"
        if [ "$stat" -eq 0 ]; then
            echo -en "\n\n\${goto 74}$location"
        else
            echo -en "\n\n\${alignc}PAUSED"
        fi
    fi

    # cover
    if [ "$rp" != "" ] && [ "$radiocover" != "" ]; then
        # use radio cover?
        echo -n "\${image $radiocover -p 0,$coverXoffset -s 62x62 -n}"
    else
        # ensure proper cover is loaded during first 9 seconds of track
        if [ "$pos" -lt 9000 ]; then
            pic=$(echo "$data" | grep "arturl: " | cut -b 16-)
            cp "$pic" '/tmp/cover.jpg'
        fi
        echo -n "\${image /tmp/cover.jpg -p 0,$coverXoffset -s 62x62 -n}"
    fi
fi

