#!/bin/bash

#params: color1, color2, min, max, value

color1=$1
color2=$2
value=$5
value=`eval $value`
part=$((100 * ($value - $3) / ($4 - $3)))

if [[ $part -gt 100 ]]; then
    part=100
fi
if [[ $part -lt 0 ]]; then
    part=0
fi

dr=$(((($color2 & 0xff0000) - ($color1 & 0xff0000)) >> 16))
dg=$(((($color2 & 0x00ff00) - ($color1 & 0x00ff00)) >> 8))
db=$(((($color2 & 0x0000ff) - ($color1 & 0x0000ff))))

col=$(($color1 + (($dr * $part / 100) << 16) + (($dg * $part / 100) << 8) + ($db * $part / 100)))
col=`echo "obase=16; "$col | bc`
echo '${color '$col'}'$value

