#!/bin/bash

# retrieves the wan address
# alternatively: `curl -s ifconfig.co`

a=$(wget -nv -O - http://ip.tupeux.com 2> /dev/null | tail)

if [[ "$a" == "" ]]; then
    echo No Address
else
    echo "$a"
fi

